baseurl: /kaceo/
timezone: Asia/Singapore
permalink: /:categories/:year/:month/:day/:title:output_ext
#permalink: pretty
markdown: kramdown

brandname: KaceO-Web
copyright: 2020 Kace Ong



defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
