# ----------------------- #
#      Main Configs       #
#       for Jekyll        #
# ----------------------- #

source: source
destination: docs
timezone: Asia/Singapore
markdown: kramdown
permalink: pretty

# ----------------------- #
#    Site Information     #
# ----------------------- #

url: http://kaceong.com
title: KaceO Awesome Portfolio
description: > # "Write an awesome description
  The home site of Kaceo
  with portfolios and developer codes.

copyright: 'Copyright &copy; 2015 Kace Ong. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
author: Kaceo

# ----------------------- #
#   Contact Information   #
# ----------------------- #

email: info@kaceong.com
social:
  -
    title: facebook
    url: https://facebook.com/ong.kace
  -
    title: github
    url: https://github.com/kaceo/kaceo
  -
    title: twitter
    url: https://twitter.com/kaceoxx
