const allmylinks=[

  {
    title: 'LittleLinks',
    url: '#',
    type: 'default',
    icon: 'littlelink.svg',
  },
  {
    title: 'Amazon Wishlist',
    url: '#',
    type: 'amazon',
    icon: 'amazon.svg',
  },
  {
    title: 'Listen on Amazon Music',
    url: '#',
    type: 'amazon-music',
    icon: 'amazon-music.svg',
  },
  {
    title: 'Apple App Store',
    url: '#',
    type: 'appstore',
    icon: 'apple.svg',
  },
  {
    title: 'Listen on Apple Music',
    url: '#',
    type: 'apple-music',
    icon: 'apple-music.svg',
  },
  {
    title: 'Listen on Apple Music',
    url: '#',
    type: 'apple-music-alt',
    icon: 'apple-music-alt.svg',
  },
  {
    title: 'Listen on Apple Podcasts',
    url: '#',
    type: 'apple-podcasts',
    icon: 'apple-podcasts.svg',
  },
  {
    title: 'Listen on Apple Podcasts',
    url: '#',
    type: 'apple-podcasts-alt',
    icon: 'apple-podcasts-alt.svg',
  },
  {
    title: 'Bandcamp',
    url: '#',
    type: 'bandcamp',
    icon: 'bandcamp.svg',
  },
  {
    title: 'Behance',
    url: '#',
    type: 'behance',
    icon: 'behance.svg',
  },
  {
    title: 'Bluesky',
    url: '#',
    type: 'bluesky',
    icon: 'bluesky.svg',
  },
  {
    title: 'Buy Me A Coffee',
    url: '#',
    type: 'coffee',
    icon: 'buy-me-a-coffee.svg',
  },
  {
    title: 'Schedule with Cal.com',
    url: '#',
    type: 'cal',
    icon: 'cal.svg',
  },
  {
    title: 'Schedule with Calendly',
    url: '#',
    type: 'calendly',
    icon: 'calendly.svg',
  },
  {
    title: 'Cash App',
    url: '#',
    type: 'cash-app',
    icon: 'cash-app-dollar.svg',
  },
  {
    title: 'Clubhouse',
    url: '#',
    type: 'clubhouse',
    icon: 'clubhouse.svg',
  },
  {
    title: 'Dev.to',
    url: '#',
    type: 'dev-to',
    icon: 'dev-to.svg',
  },
  {
    title: 'Discord',
    url: '#',
    type: 'discord',
    icon: 'discord.svg',
  },
  {
    title: 'Dribbble',
    url: '#',
    type: 'dribbble',
    icon: 'dribbble.svg',
  },
  {
    title: 'Shop on Etsy',
    url: '#',
    type: 'etsy',
    icon: 'etsy.svg',
  },
  {
    title: 'Find us on Facebook',
    url: '#',
    type: 'faceb',
    icon: 'facebook.svg',
  },
  {
    title: 'Chat on Messenger',
    url: '#',
    type: 'messenger',
    icon: 'messenger.svg',
  },
  {
    title: 'Figma Community',
    url: '#',
    type: 'figma',
    icon: 'figma.svg',
  },
  {
    title: 'Fiverr Gig',
    url: '#',
    type: 'fiverr',
    icon: 'fiverr.svg',
  },
  {
    title: 'Flickr',
    url: '#',
    type: 'flickr',
    icon: 'flickr.svg',
  },
  {
    title: 'GitHub',
    url: '#',
    type: 'github',
    icon: 'github.svg',
  },
  {
    title: 'GitLab',
    url: '#',
    type: 'gitlab',
    icon: 'gitlab.svg',
  },
  {
    title: 'Goodreads',
    url: '#',
    type: 'goodreads',
    icon: 'goodreads.svg',
  },
  {
    title: 'View in Google Drive',
    url: '#',
    type: 'google-black',
    icon: 'google-drive.svg',
  },
  {
    title: 'Google Play Store',
    url: '#',
    type: 'playstore',
    icon: 'google-play.svg',
  },
  {
    title: 'Listen on Google Podcasts',
    url: '#',
    type: 'google-podcasts',
    icon: 'google-podcasts.svg',
  },
  {
    title: 'Google Scholar',
    url: '#',
    type: 'google-scholar',
    icon: 'google-scholar.svg',
  },
  {
    title: 'Guilded',
    url: '#',
    type: 'guilded',
    icon: 'guilded.svg',
  },
  {
    title: 'Hashnode',
    url: '#',
    type: 'hashnode',
    icon: 'hashnode.svg',
  },
  {
    title: 'Instagram',
    url: '#',
    type: 'instagram',
    icon: 'instagram.svg',
  },
  {
    title: 'Kickstarter',
    url: '#',
    type: 'kickstarter',
    icon: 'kickstarter.svg','
  },
  {
    title: 'Kit',
    url: '#',
    type: 'kit',
    icon: 'kit.svg',
  },
  {
    title: 'Ko-fi',
    url: '#',
    type: 'ko-fi',
    icon: 'ko-fi.svg',
  },
  {
    title: 'Last.fm',
    url: '#',
    type: 'last-fm',
    icon: 'last-fm.svg',
  },
  {
    title: 'Letterboxd',
    url: '#',
    type: 'letterboxd',
    icon: 'letterboxd.svg',
  },
  {
    title: 'Line',
    url: '#',
    type: 'line',
    icon: 'line.svg',
  },
  {
    title: 'LinkedIn',
    url: '#',
    type: 'linked',
    icon: 'linkedin.svg',
  },
  {
    title: 'Mailchimp',
    url: '#',
    type: 'mailchimp',
    icon: 'mailchimp.svg',
  },
  {
    title: 'Mastadon',
    url: '#',
    type: 'mastadon',
    icon: 'mastadon.svg',
  },
  {
    title: 'Medium',
    url: '#',
    type: 'medium',
    icon: 'medium.svg',
  },
  {
    title: 'Notion',
    url: '#',
    type: 'notion',
    icon: 'notion.svg',
  },
  {
    title: 'OnlyFans (18+)',
    url: '#',
    type: 'onlyfans',
    icon: 'onlyfans.svg',
  },
  {
    title: 'Patreon',
    url: '#',
    type: 'patreon',
    icon: 'patreon.svg',
  },
  {
    title: 'PayPal',
    url: '#',
    type: 'paypal',
    icon: 'paypal.svg','
  },
  {
    title: 'Pinterest',
    url: '#',
    type: 'pinterest',
    icon: 'pinterest.svg',
  },
  {
    title: 'Post.news',
    url: '#',
    type: 'post-news',
    icon: 'post-news.svg',
  },
  {
    title: 'Product Hunt',
    url: '#',
    type: 'product-hunt',
    icon: 'product-hunt.svg',
  },
  {
    title: 'Read.cv',
    url: '#',
    type: 'read-cv',
    icon: 'read-cv.svg',
  },
  {
    title: 'Redbubble',
    url: '#',
    type: 'redbubble',
    icon: 'redbubble.svg',
  },
  {
    title: 'Reddit',
    url: '#',
    type: 'reddit',
    icon: 'reddit.svg',
  },
  {
    title: 'Buy with Shop',
    url: '#',
    type: 'shop',
    icon: 'shop.svg',
  },
  {
    title: 'Signal',
    url: '#",
    type: 'signal',
    icon: 'signal.svg',
  },
  {
    title: 'Skoob',
    url: '#',
    type: 'skoob',
    icon: 'skoob.svg',
  },
  {
    title: 'Join Slack',
    url: '#',
    type: 'slack',
    icon: 'slack.svg',
  },
  {
    title: 'Snapchat',
    url: '#',
    type: 'snapchat',
    icon: 'snapchat.svg',
  },
  {
    title: 'SoundCloud',
    url: '#',
    type: 'soundcloud',
    icon: 'soundcloud.svg',
  },
  {
    title: 'Listen on Spotify',
    url: '#',
    type: 'spotify',
    icon: 'spotify.svg',
  },
  {
    title: 'Listen on Spotify',
    url: '#',
    type: 'spotify-alt',
    icon: 'spotify-alt.svg',
  },
  {
    title: 'Buy with Square',
    url: '#',
    type: 'square',
    icon: 'square.svg',
  },
  {
    title: 'Steam',
    url: '#',
    type: 'steam',
    icon: 'steam.svg',
  },
  {
    title: 'Strava',
    url: '#',
    type: 'strava',
    icon: 'strava.svg',
  },
  {
    title: 'Substack',
    url: '#',
    type: 'substack',
    icon: 'substack.svg',
  },
  {
    title: 'Telegram',
    url: '#',
    type: 'telegram',
    icon: 'telegram.svg',
  },
  {
    title: 'Threema',
    url: '#',
    type: 'threema',
    icon: 'threema.svg',
  },
  {
    title: 'Tiktok',
    url: '#',
    type: 'tiktok',
    icon: 'tiktok.svg',
  },
  {
    title: 'Trello',
    url: '#',
    type: 'trello',
    icon: 'trello.svg',
  },
  {
    title: 'Tumblr',
    url: '#',
    type: 'tumblr',
    icon: 'tumblr.svg',
  },
  {
    title: 'Twitch',
    url: '#',
    type: 'twitch',
    icon: 'twitch.svg',
  },
  {
    title: 'Twitter',
    url: '#',
    type: 'twitter',
    icon: 'twitter.svg',
  },
  {
    title: 'Unsplash',
    url: '#',
    type: 'unsplash',
    icon: 'unsplash.svg',
  },
  {
    title: 'Untappd',
    url: '#',
    type: 'untappd',
    icon: 'untappd.svg',
  },
  {
    title: 'Upwork',
    url: '#',
    type: 'upwork',
    icon: 'upwork.svg',
  },
  {
    title: 'Venmo',
    url: '#',
    type: 'venmo',
    icon: 'venmo.svg',
  },
  {
    title: 'Vimeo',
    url: '#',
    type: 'vimeo',
    icon: 'vimeo.svg',
  },
  {
    title: 'VRChat',
    url: '#',
    type: 'vrchat',
    icon: 'vrchat.svg',
  },
  {
    title: 'VSCO',
    url: '#',
    type: 'vsco',
    icon: 'vsco.svg',
  },
  {
    title: 'WhatsApp',
    url: '#',
    type: 'whatsapp',
    icon: 'whatsapp.svg',
  },
  {
    title: 'WordPress',
    url: '#',
    type: 'wordpress',
    icon: 'wordpress.svg',
  },
  {
    title: 'Xing',
    url: '#',
    type: 'xing',
    icon: 'xing.svg',
  },
  {
    title: 'YouTube',
    url: '#',
    type: 'yt',
    icon: 'youtube.svg',
  },
  {
    title: 'Listen on YouTube Music',
    url: '#',
    type: 'yt',
    icon: 'youtube-music.svg',
  },
  {
    title: 'Join Zoom Webinar',
    url: '#',
    type: 'zoom',
    icon: 'zoom.svg',
  },
  {
    title: 'Read Our Blogs',
    url: '#',
    type: 'default',
    icon: 'generic-blog.svg',
  },
  {
    title: 'Event RSVP',
    url: '#',
    type: 'default',
    icon: 'generic-calendar.svg',
  },
  {
    title: 'Download File',
    url: '#',
    type: 'default',
    icon: 'generic-cloud.svg',
  },
  {
    title: 'View the Code',
    url: '#',
    type: 'default',
    icon: 'generic-code.svg',
  },
  {
    title: 'Homelab Setup',
    url: '#',
    type: 'default',
    icon: 'generic-computer.svg',
  },
  {
    title: 'Email Us',
    url: '#',
    type: 'default',
    icon: 'generic-email.svg',
  },
  {
    title: 'Email Us',
    url: '#',
    type: 'default',
    icon: 'generic-email-alt.svg',
  },
  {
    title: 'Visit Homepage',
    url: '#',
    type: 'default',
    icon: 'generic-homepage.svg',
  },
  {
    title: 'Get Directions',
    url: '#',
    type: 'default',
    icon: 'generic-map.svg',
  },
  {
    title: 'Call Us',
    url: '#',
    type: 'default',
    icon: 'generic-phone.svg',
  },
  {
    title: 'Leave Us a Review',
    url: '#',
    type: 'default',
    icon: 'generic-review.svg',
  },
  {
    title: 'RSS Subscriber',
    url: '#',
    type: 'default',
    icon: 'generic-rss.svg',
  },
  {
    title: 'Visit Our Shop',
    url: '#',
    type: 'default',
    icon: 'generic-shopping-bag.svg',
  },
  {
    title: '10% Discount',
    url: '#',
    type: 'default',
    icon: 'generic-shopping-tag.svg',
  },
  {
    title: 'Send Us a Message',
    url: '#',
    type: 'default',
    icon: 'generic-sms.svg',
  },
  {
    title: 'Visit Website',
    url: '#',
    type: 'default',
    icon: 'generic-website.svg',
  },
]
